added beautiful image
Sheridan-CS-Club/club-website pull request #2
Opened 2024-12-01 22:27 UTC by kumankai

2024-12-06 18:32 UTC, AmirGhiassian requested changes
Looks lovely, maybe just one thing. Change the text since now we have a pull request and maybe we can get more users to commit to the repository

2024-12-06 18:32 UTC, AmirGhiassian commented on src/App.tsx
> -          Yeah this site is empty. Get to codin club members ;)
Why was the ")" removed 😭
It was a winkyyy faceeeeee

2024-12-06 18:50 UTC, kumankai commented on src/App.tsx
> -          Yeah this site is empty. Get to codin club members ;)
Sorry, thought it was a type

2024-12-10 20:47 UTC, AmirGhiassian approved these changes
;)

2024-12-10 20:48 UTC, merged